language: go

go:
        - "1.11"
        - "1.12"
        - "1.13"

script:
        - go test -v -race -cover -bench . ./diam/...

install:
        - go get -v golang.org/x/net/context
        - go get -v golang.org/x/tools/cmd/cover
        - go get -v github.com/ishidawataru/sctp
